### PR TITLE
- Add some extensions for the grammar and preview.

### PR DESCRIPTION
**Pull request by lmcbout**
issue #13
Customer request to handle other extensions. 
Signed-off-by: Jacques Bouthillier <jacques.bouthllier@ericsson.com>

### CODE REVIEW

**Review by AlexTugarev — APPROVED** [review]
LGTM! Thanks @lmcbout!

**Comment by lmcbout** [comment]
Hi @AlexTugarev Our customer is using "latest", would you like to create a "Latest" version or we can take care of it.
Thanks

**Comment by AlexTugarev** [comment]
@lmcbout, it would be great if you would publish latest when needed.

**Comment by lmcbout** [comment]
@AlexTugarev  Ok we will take care of it.

**Pull request merged**
